#!/usr/bin/env bash
# Bash script that uses 'ssh' to connect to your server
# using the private key ~/.ssh/school with the user 'ubuntu'

# The server IP address/hostname
server="54.198.36.70"

# The private key file path
private_key="~/.ssh/school"

# Set the username
username="ubuntu"

# SSH command using variables and flag -i
ssh -i $private_key $username@$server
